# Books Data

In [1]:
# importing libraries
import pandas as pd
from pathlib import Path
pd.set_option('display.max_columns', None)

In [2]:
# paths
INTERIM = Path("../data/interim")

In [5]:
a = pd.read_parquet(INTERIM / "editions.parquet")
b = pd.read_parquet(INTERIM / "editions_extra.parquet")

overlap = set(a.work_id) & set(b.work_id)
print(f"editions   {len(a):,} + {len(b):,}")
print(f"overlapping work_ids: {len(overlap):,}")

editions   1,244,611 + 792,133
overlapping work_ids: 61

In [6]:
a = pd.read_parquet(INTERIM / "english_works.parquet")
b = pd.read_parquet(INTERIM / "english_works_extra.parquet")

works = pd.concat([a, b], ignore_index=True)
dupes = works.work_id.duplicated(keep=False).sum()
print(f"{len(works):,} works, {dupes} duplicate rows")

works = works.sort_values("ratings_total", ascending=False) \
             .drop_duplicates("work_id", keep="first") \
             .reset_index(drop=True)
print(f"{len(works):,} after dedup")

1,002,652 works, 90 duplicate rows
1,002,607 after dedup

In [7]:
for q in ["Dorian Gray", "One Hundred Years of Solitude", "Ivan Ily", "Little Prince"]:
    hits = works[works.title.str.contains(q, case=False, na=False, regex=False)]
    if hits.empty:
        print(f"{q}: NO MATCH")
    else:
        r = hits.nlargest(1, "ratings_total").iloc[0]
        print(f"{q}: {r.title} ({r.ratings_total:,})")

Dorian Gray: The Picture of Dorian Gray (683,950)
One Hundred Years of Solitude: One Hundred Years of Solitude (578,926)
Ivan Ily: The Death of Ivan Ilych (55,051)
Little Prince: The Little Prince (878,752)

In [9]:
works = works.drop(columns=["genre"])

In [10]:
print("only in a:", set(a.columns) - set(b.columns))
print("only in b:", set(b.columns) - set(a.columns))

only in a: {'rating_weighted'}
only in b: {'avg_rating', '_has_desc', '_is_en'}

In [11]:
b = b.rename(columns={"avg_rating": "rating_weighted"})
b = b.drop(columns=["_has_desc", "_is_en"])

works = pd.concat([a, b], ignore_index=True) \
          .sort_values("ratings_total", ascending=False) \
          .drop_duplicates("work_id", keep="first") \
          .reset_index(drop=True)

if "genre" in works.columns:
    works = works.drop(columns=["genre"])

print(set(a.columns) ^ set(b.columns) or "columns match")
print(f"{len(works):,} works")

columns match
1,002,607 works

In [12]:
out = INTERIM / "english_works_all.parquet"
works.to_parquet(out, index=False)

print(f"{len(works):,} works -> {out}  ({out.stat().st_size / 1e6:.0f} MB)")

check = pd.read_parquet(out)
assert len(check) == len(works)
assert check.work_id.is_unique
print("verified")

1,002,607 works -> ../data/interim/english_works_all.parquet  (1561 MB)
verified

## Books File Analysis

In [6]:
books = pd.read_parquet(
    INTERIM / "english_works_all.parquet",
    columns=["work_id", "title", "authors", "description", "genres",
             "tags", "tag_counts", "book_id_all", "series", "similar_books",
             "ratings_total", "reviews_total", "rating_weighted",
             "year_first", "pages_median", "editions"],
)

In [7]:
books.head()

,work_id,title,authors,description,genres,tags,tag_counts,book_id_all,series,similar_books,ratings_total,reviews_total,rating_weighted,year_first,pages_median,editions
0,2792775,"The Hunger Games (The Hunger Games, #1)","[{'author_id': '153394', 'role': ''}]",Winning will make you famous.\nLosing means ce...,[young_adult],"[young-adult, fiction, dystopian, dystopia, fa...","[3315957, 1766978, 1659179, 1416250, 1385816, ...","[10197660, 10255274, 10282880, 10327392, 10616...",[339872],"[1902241, 146499, 954674, 9917938, 10165727, 7...",5064668,156478,4.34,2008.0,384.0,126
1,4640799,Harry Potter and the Sorcerer's Stone (Harry P...,"[{'author_id': '1077326', 'role': ''}, {'autho...",Harry Potter's life is miserable. His parents ...,[fantasy_paranormal],"[fantasy, young-adult, fiction, harry-potter, ...","[11847821, 3718993, 3316936, 2144163, 1311521,...","[10180184, 1033918, 10385172, 10435027, 110197...",[167817],"[13830, 127586, 121822, 37586, 6164358, 807968...",4970387,78500,4.45,1997.0,285.0,244
2,3212258,"Twilight (Twilight, #1)","[{'author_id': '941441', 'role': ''}]",About three things I was absolutely positive.\...,[fantasy_paranormal],"[young-adult, fantasy, vampires, ya, fiction, ...","[1529970, 1334012, 689122, 611516, 586966, 483...","[10244455, 1029083, 1035885, 10771500, 1111273...",[165622],"[1326258, 140077, 35729, 30123413, 11260526, 9...",3991256,95594,3.57,2005.0,476.0,92
3,3275794,To Kill a Mockingbird,"[{'author_id': '1825', 'role': ''}]",The unforgettable novel of a childhood in a sl...,[history_biography],"[classics, classic, historical-fiction, clàssi...","[6524280, 1344924, 1026960, 762264, 640710, 53...","[10257528, 10370664, 10623852, 10754520, 11192...",[735877],"[1934, 2156, 15638, 53835, 77142, 5114, 116020...",3399207,73801,4.26,1960.0,331.0,210
4,245494,The Great Gatsby,"[{'author_id': '3190', 'role': ''}]","THE GREAT GATSBY, F. Scott Fitzgerald's third ...","[biography, fiction, historical fiction, histo...","[classics, fiction, classic, literature, schoo...","[10839416, 5134512, 1884073, 903665, 887568, 8...","[10125603, 10194387, 10301147, 10304725, 10381...",[],"[48203, 337113, 176972, 188087, 10956, 12722, ...",2841340,52125,3.89,1925.0,189.5,328

In [8]:
books.shape

(1002607, 16)

In [9]:
books.shape
books['work_id'].nunique()
if books.shape[0] == books['work_id'].nunique():
    print('work id is primary key.')
else:
    print('check for duplicates')

work id is primary key.

In [10]:
books.columns

Index(['work_id', 'title', 'authors', 'description', 'genres', 'tags',
       'tag_counts', 'book_id_all', 'series', 'similar_books', 'ratings_total',
       'reviews_total', 'rating_weighted', 'year_first', 'pages_median',
       'editions'],
      dtype='str')

In [11]:
titles = ["Little Prince", "Picture of Dorian Gray"]

for q in titles:
    hits = books[books.title.str.contains(q, case=False, na=False, regex=False)]
    if hits.empty:
        print(f"=== {q}: NO MATCH\n")
        continue

    r = hits.nlargest(1, "ratings_total").iloc[0]

    print(f"=== {r.title}")
    print(f"rating   {r.rating_weighted:.2f}   ratings {r.ratings_total:,}   reviews {r.reviews_total:,}")
    print(f"genres   {list(r.genres)}")
    print(f"\ndescription:\n{r.description}")
    print(f"\ntags ({len(r.tags)}):")
    for t, c in zip(r.tags, r.tag_counts):
        print(f"  {c:>10,}  {t}")
    print("\n" + "-" * 70 + "\n")

=== The Little Prince
rating   4.28   ratings 878,752   reviews 24,880
genres   ['children']

description:
Moral allegory and spiritual autobiography, The Little Prince is the most translated book in the French language. With a timeless charm it tells the story of a little boy who leaves the safety of his own tiny planet to travel the universe, learning the vagaries of adult behaviour through a series of extraordinary encounters. His personal odyssey culminates in a voyage to Earth and further adventures.

tags (77):
   3,833,138  classics
   2,121,014  fiction
   1,531,321  fantasy
   1,092,573  childrens
     897,490  children
     749,796  classic
     636,833  french
     487,124  children-s
     448,546  young-adult
     429,403  philosophy
     385,261  children-s-books
     300,490  childhood
     296,692  literature
     279,183  kids
     237,639  childrens-books
     213,294  french-literature
     197,806  school
     181,090  1001-books
     174,357  france
     150,046  favorite
     150,043  ya
     148,241  novel
     122,219  children-s-literature
     113,828  adventure
     107,460  middle-grade
     107,062  children-s-lit
     107,062  1001
     105,072  kids-books
      96,714  20th-century
      96,316  favorite-books
      94,326  read-in-2016
      91,540  français
      84,774  read-in-2015
      84,561  favoritos
      83,182  inspirational
      82,383  5-stars
      81,988  juvenile
      81,590  read-for-school
      79,998  favourite
      79,818  my-library
      79,600  to-re-read
      77,610  children-books
      74,611  translated
      74,028  childhood-favorites
      74,025  picture-books
      73,232  french-lit
      71,673  read-in-french
      69,252  childrens-lit
      68,091  short-stories
      63,674  read-in-2017
      60,894  childrens-literature
      60,496  science-fiction
      60,496  childhood-books
      59,302  faves
      58,506  classic-literature
      58,108  1001-books-to-read-before-you-die
      57,895  for-school
      56,516  read-more-than-once
      55,319  high-school
      54,128  youth
      53,730  english
      53,332  to-reread
      53,332  must-read
      52,536  stand-alone
      51,740  borrowed
      50,944  illustrated
      49,750  francais
      49,352  clásicos
      49,352  sci-fi
      48,954  favs
      45,770  finished
      45,557  all-time-favourites
      44,178  read-in-2014
      44,178  own-it
      43,169  my-favorites
      42,586  classici
      42,586  fairy-tales

----------------------------------------------------------------------

=== The Picture of Dorian Gray
rating   4.06   ratings 683,950   reviews 19,689
genres   ['biography', 'crime', 'fantasy', 'fiction', 'historical fiction', 'history', 'mystery', 'paranormal', 'thriller']

description:
Written in his distinctively dazzling manner, Oscar Wilde's story of a fashionable young man who sells his soul for eternal youth and beauty is the author's most popular work. The tale of Dorian Gray's moral disintegration caused a scandal when it first appeared in 1890, but though Wilde was attacked for the novel's corrupting influence, he responded that there is, in fact, "a terrible moral in Dorian Gray." Just a few years later, the book and the aesthetic/moral dilemma it presented became issues in the trials occasioned by Wilde's homosexual liaisons, which resulted in his imprisonment. Of Dorian Gray's relationship to autobiography, Wilde noted in a letter, "Basil Hallward is what I think I am: Lord Henry what the world thinks me: Dorian what I would like to be--in other ages, perhaps."

tags (74):
   6,545,685  classics
   2,408,747  fiction
   1,049,695  classic
     692,210  horror
     551,105  fantasy
     471,227  literature
     366,390  gothic
     232,839  19th-century
     168,360  my-ebooks
     166,290  1001-books
     162,283  classic-literature
     148,386  english
     144,210  british
     134,550  novel
     129,720  school
     125,235  victorian
     122,953  british-literature
     122,130  historical-fiction
     120,750  adult
     117,300  classics-to-read
     105,915  lgbt
      99,881  irish
      99,705  1001
      96,255  my-library
      90,045  historical
      87,975  oscar-wilde
      87,630  english-literature
      82,110  literary-fiction
      78,315  adult-fiction
      73,140  mystery
      72,450  read-in-english
      71,063  philosophy
      70,725  classic-lit
      69,345  to-read-classics
      69,000  rory-gilmore-reading-challenge
      66,930  favorite-books
      65,550  england
      64,860  classic-fiction
      63,825  paranormal
      62,790  read-for-school
      61,755  supernatural
      61,755  favorite
      60,339  to-re-read
      58,650  read-in-2016
      58,341  read-in-2015
      58,129  drama
      57,960  classici
      57,270  ireland
      57,270  audio
      55,200  1001-books-to-read-before-you-die
      53,820  general-fiction
      52,785  own-it
      51,750  read-in-2014
      50,025  for-school
      49,849  lgbtq
      49,680  e-books
      48,645  favourite
      47,955  magical-realism
      47,822  read-in-2017
      47,610  e-book
      46,920  literary
      45,195  clásicos
      44,160  the-classics
      43,470  rory-gilmore-challenge
      43,125  high-school
      42,471  to-reread
      42,435  queer
      42,090  dark
      40,674  tbr
      40,196  irish-literature
      39,330  must-read
      38,809  on-my-shelf
      38,295  faves
      37,950  my-bookshelf

----------------------------------------------------------------------

In [12]:
gm = pd.read_parquet("../data/raw/book_genres.parquet")
gm_dict = dict(zip(gm.book_id, gm.genres))

def map_genres(book_ids):
    out = set()
    for b in book_ids:
        out.update(gm_dict.get(str(b), []))
    return sorted(out)

books["genres_map"] = books.book_id_all.apply(map_genres)

print(f"books with mapped genres: {books.genres_map.apply(len).gt(0).mean():.1%}")
print(books.genres_map.explode().value_counts().to_string())

books with mapped genres: 84.2%
genres_map
fiction               457763
romance               272291
non-fiction           258174
biography             255241
historical fiction    255241
history               255241
fantasy               212175
paranormal            212175
crime                 183081
mystery               183081
thriller              183081
young-adult           125700
children              123578
comics                 72597
graphic                72597
poetry                 36905

In [13]:
lp = books[books.title.str.contains("Little Prince", case=False, na=False, regex=False)] \
        .nlargest(1, "ratings_total").iloc[0]

print("from files:", list(lp.genres))
print("from map  :", list(lp.genres_map))

from files: ['children']
from map  : ['children', 'fantasy', 'fiction', 'paranormal', 'young-adult']

In [14]:
books["genres"] = [
    list(m) if len(m) else list(g)
    for m, g in zip(books.genres_map, books.genres)
]
books = books.drop(columns=["genres_map"])

print(books.genres.explode().value_counts().to_string())
print(f"\nno genre: {books.genres.apply(len).eq(0).mean():.1%}")

genres
fiction               457763
romance               272291
non-fiction           258174
biography             255241
historical fiction    255241
history               255241
fantasy               212175
paranormal            212175
crime                 183081
mystery               183081
thriller              183081
young-adult           125700
children              123578
comics                 72597
graphic                72597
poetry                 36905

no genre: 15.8%

In [15]:
books.head()

,work_id,title,authors,description,genres,tags,tag_counts,book_id_all,series,similar_books,ratings_total,reviews_total,rating_weighted,year_first,pages_median,editions
0,2792775,"The Hunger Games (The Hunger Games, #1)","[{'author_id': '153394', 'role': ''}]",Winning will make you famous.\nLosing means ce...,"[crime, fantasy, fiction, mystery, paranormal,...","[young-adult, fiction, dystopian, dystopia, fa...","[3315957, 1766978, 1659179, 1416250, 1385816, ...","[10197660, 10255274, 10282880, 10327392, 10616...",[339872],"[1902241, 146499, 954674, 9917938, 10165727, 7...",5064668,156478,4.34,2008.0,384.0,126
1,4640799,Harry Potter and the Sorcerer's Stone (Harry P...,"[{'author_id': '1077326', 'role': ''}, {'autho...",Harry Potter's life is miserable. His parents ...,"[children, crime, fantasy, fiction, mystery, p...","[fantasy, young-adult, fiction, harry-potter, ...","[11847821, 3718993, 3316936, 2144163, 1311521,...","[10180184, 1033918, 10385172, 10435027, 110197...",[167817],"[13830, 127586, 121822, 37586, 6164358, 807968...",4970387,78500,4.45,1997.0,285.0,244
2,3212258,"Twilight (Twilight, #1)","[{'author_id': '941441', 'role': ''}]",About three things I was absolutely positive.\...,"[fantasy, fiction, paranormal, romance, young-...","[young-adult, fantasy, vampires, ya, fiction, ...","[1529970, 1334012, 689122, 611516, 586966, 483...","[10244455, 1029083, 1035885, 10771500, 1111273...",[165622],"[1326258, 140077, 35729, 30123413, 11260526, 9...",3991256,95594,3.57,2005.0,476.0,92
3,3275794,To Kill a Mockingbird,"[{'author_id': '1825', 'role': ''}]",The unforgettable novel of a childhood in a sl...,"[biography, crime, fiction, historical fiction...","[classics, classic, historical-fiction, clàssi...","[6524280, 1344924, 1026960, 762264, 640710, 53...","[10257528, 10370664, 10623852, 10754520, 11192...",[735877],"[1934, 2156, 15638, 53835, 77142, 5114, 116020...",3399207,73801,4.26,1960.0,331.0,210
4,245494,The Great Gatsby,"[{'author_id': '3190', 'role': ''}]","THE GREAT GATSBY, F. Scott Fitzgerald's third ...","[biography, fiction, historical fiction, histo...","[classics, fiction, classic, literature, schoo...","[10839416, 5134512, 1884073, 903665, 887568, 8...","[10125603, 10194387, 10301147, 10304725, 10381...",[],"[48203, 337113, 176972, 188087, 10956, 12722, ...",2841340,52125,3.89,1925.0,189.5,328

In [16]:
titles = ["Little Prince", "Picture of Dorian Gray", "One Hundred Years of Solitude",
          "Ivan Ily", "Hitchhiker"]

for q in titles:
    hits = books[books.title.str.contains(q, case=False, na=False, regex=False)]
    if hits.empty:
        print(f"=== {q}: NO MATCH\n")
        continue

    r = hits.nlargest(1, "ratings_total").iloc[0]

    print(f"=== {r.title}")
    print(f"rating   {r.rating_weighted:.2f}   ratings {r.ratings_total:,}   reviews {r.reviews_total:,}")
    print(f"genres   {list(r.genres)}")
    print(f"\ndescription:\n{r.description}")
    print(f"\ntags ({len(r.tags)}):")
    for t, c in zip(r.tags, r.tag_counts):
        print(f"  {c:>10,}  {t}")
    print("\n" + "-" * 70 + "\n")

=== The Little Prince
rating   4.28   ratings 878,752   reviews 24,880
genres   ['children', 'fantasy', 'fiction', 'paranormal', 'young-adult']

description:
Moral allegory and spiritual autobiography, The Little Prince is the most translated book in the French language. With a timeless charm it tells the story of a little boy who leaves the safety of his own tiny planet to travel the universe, learning the vagaries of adult behaviour through a series of extraordinary encounters. His personal odyssey culminates in a voyage to Earth and further adventures.

tags (77):
   3,833,138  classics
   2,121,014  fiction
   1,531,321  fantasy
   1,092,573  childrens
     897,490  children
     749,796  classic
     636,833  french
     487,124  children-s
     448,546  young-adult
     429,403  philosophy
     385,261  children-s-books
     300,490  childhood
     296,692  literature
     279,183  kids
     237,639  childrens-books
     213,294  french-literature
     197,806  school
     181,090  1001-books
     174,357  france
     150,046  favorite
     150,043  ya
     148,241  novel
     122,219  children-s-literature
     113,828  adventure
     107,460  middle-grade
     107,062  children-s-lit
     107,062  1001
     105,072  kids-books
      96,714  20th-century
      96,316  favorite-books
      94,326  read-in-2016
      91,540  français
      84,774  read-in-2015
      84,561  favoritos
      83,182  inspirational
      82,383  5-stars
      81,988  juvenile
      81,590  read-for-school
      79,998  favourite
      79,818  my-library
      79,600  to-re-read
      77,610  children-books
      74,611  translated
      74,028  childhood-favorites
      74,025  picture-books
      73,232  french-lit
      71,673  read-in-french
      69,252  childrens-lit
      68,091  short-stories
      63,674  read-in-2017
      60,894  childrens-literature
      60,496  science-fiction
      60,496  childhood-books
      59,302  faves
      58,506  classic-literature
      58,108  1001-books-to-read-before-you-die
      57,895  for-school
      56,516  read-more-than-once
      55,319  high-school
      54,128  youth
      53,730  english
      53,332  to-reread
      53,332  must-read
      52,536  stand-alone
      51,740  borrowed
      50,944  illustrated
      49,750  francais
      49,352  clásicos
      49,352  sci-fi
      48,954  favs
      45,770  finished
      45,557  all-time-favourites
      44,178  read-in-2014
      44,178  own-it
      43,169  my-favorites
      42,586  classici
      42,586  fairy-tales

----------------------------------------------------------------------

=== The Picture of Dorian Gray
rating   4.06   ratings 683,950   reviews 19,689
genres   ['biography', 'crime', 'fantasy', 'fiction', 'historical fiction', 'history', 'mystery', 'paranormal', 'thriller']

description:
Written in his distinctively dazzling manner, Oscar Wilde's story of a fashionable young man who sells his soul for eternal youth and beauty is the author's most popular work. The tale of Dorian Gray's moral disintegration caused a scandal when it first appeared in 1890, but though Wilde was attacked for the novel's corrupting influence, he responded that there is, in fact, "a terrible moral in Dorian Gray." Just a few years later, the book and the aesthetic/moral dilemma it presented became issues in the trials occasioned by Wilde's homosexual liaisons, which resulted in his imprisonment. Of Dorian Gray's relationship to autobiography, Wilde noted in a letter, "Basil Hallward is what I think I am: Lord Henry what the world thinks me: Dorian what I would like to be--in other ages, perhaps."

tags (74):
   6,545,685  classics
   2,408,747  fiction
   1,049,695  classic
     692,210  horror
     551,105  fantasy
     471,227  literature
     366,390  gothic
     232,839  19th-century
     168,360  my-ebooks
     166,290  1001-books
     162,283  classic-literature
     148,386  english
     144,210  british
     134,550  novel
     129,720  school
     125,235  victorian
     122,953  british-literature
     122,130  historical-fiction
     120,750  adult
     117,300  classics-to-read
     105,915  lgbt
      99,881  irish
      99,705  1001
      96,255  my-library
      90,045  historical
      87,975  oscar-wilde
      87,630  english-literature
      82,110  literary-fiction
      78,315  adult-fiction
      73,140  mystery
      72,450  read-in-english
      71,063  philosophy
      70,725  classic-lit
      69,345  to-read-classics
      69,000  rory-gilmore-reading-challenge
      66,930  favorite-books
      65,550  england
      64,860  classic-fiction
      63,825  paranormal
      62,790  read-for-school
      61,755  supernatural
      61,755  favorite
      60,339  to-re-read
      58,650  read-in-2016
      58,341  read-in-2015
      58,129  drama
      57,960  classici
      57,270  ireland
      57,270  audio
      55,200  1001-books-to-read-before-you-die
      53,820  general-fiction
      52,785  own-it
      51,750  read-in-2014
      50,025  for-school
      49,849  lgbtq
      49,680  e-books
      48,645  favourite
      47,955  magical-realism
      47,822  read-in-2017
      47,610  e-book
      46,920  literary
      45,195  clásicos
      44,160  the-classics
      43,470  rory-gilmore-challenge
      43,125  high-school
      42,471  to-reread
      42,435  queer
      42,090  dark
      40,674  tbr
      40,196  irish-literature
      39,330  must-read
      38,809  on-my-shelf
      38,295  faves
      37,950  my-bookshelf

----------------------------------------------------------------------

=== One Hundred Years of Solitude
rating   4.04   ratings 578,926   reviews 21,590
genres   ['biography', 'fantasy', 'fiction', 'historical fiction', 'history', 'paranormal', 'romance']

description:
Probably Garcia Marquez finest and most famous work. One Hundred Years of Solitudetells the story of the rise and fall, birth and death of a mythical town of Macondo through the history of the Buendia family. Inventive, amusing, magnetic, sad, alive with unforgettable men and women, and with a truth and understanding that strike the soul. One Hundred Years of Solitudeis a masterpiece of the art of fiction.

tags (73):
   1,392,270  fiction
   1,114,141  classics
     377,522  magical-realism
     233,189  literature
     182,360  classic
     157,722  fantasy
     128,039  historical-fiction
     103,297  latin-america
      99,521  novel
      89,045  spanish
      72,750  1001-books
      72,362  magic-realism
      70,616  latin-american
      62,856  literary-fiction
      48,306  colombia
      45,008  my-library
      44,814  did-not-finish
      43,068  south-america
      42,874  20th-century
      42,680  1001
      41,994  روايات
      39,576  modern-classics
      37,829  latin-american-literature
      37,636  nobel-prize
      37,442  translated
      36,860  adult-fiction
      35,890  adult
      35,398  classics-to-read
      34,144  contemporary
      33,963  nobel
      32,592  favorite
      32,592  literary
      31,622  rory-gilmore-reading-challenge
      31,040  to-read-fiction
      30,264  historical
      30,070  didn-t-finish
      29,682  to-re-read
      28,906  favorite-books
      28,518  español
      28,518  never-finished
      28,130  general-fiction
      27,354  classic-literature
      26,772  favoritos
      26,772  spanish-literature
      26,384  1001-books-to-read-before-you-die
      25,996  gabriel-garcia-marquez
      25,995  to-read-classics
      25,414  contemporary-fiction
      25,220  gave-up-on
      25,026  must-read
      24,638  couldn-t-finish
      24,250  school
      22,503  romance
      22,310  lit
      21,340  own-it
      21,340  drama
      20,771  translation
      20,564  bookclub
      20,370  world-literature
      20,176  south-american
      19,788  to-reread
      19,012  latin-american-lit
      18,818  favourite
      18,624  colombian
      18,236  rory-gilmore-challenge
      17,460  marquez
      17,072  finished
      17,072  classic-fiction
      16,490  1960s
      16,101  family
      15,520  fiction-to-read
      15,326  1001-books-you-must-read-before-you
      15,326  oprah-s-book-club

----------------------------------------------------------------------

=== The Death of Ivan Ilych
rating   4.04   ratings 55,051   reviews 2,614
genres   ['biography', 'fiction', 'historical fiction', 'history']

description:
Hailed as one of the world's supreme masterpieces on the subject of death and dying, The Death of Ivan Ilyich is the story of a worldly careerist, a high court judge who has never given the inevitability of his dying so much as a passing thought. But one day, death announces itself to him, and to his shocked surprise, he is brought face to face with his own mortality.
How, Tolstoy asks, does an unreflective man confront his one and only moment of truth?
This short novel was an artistic culmination of a profound spiritual crisis in Tolstoy's life, a nine-year period following the publication of Anna Karenina during which he wrote not a word of fiction.
A thoroughly absorbing and, at times, terrifying glimpse into the abyss of death, it is also a strong testament to the possibility of finding spiritual salvation.

tags (80):
      27,845  literature
      22,250  classic
      17,266  russian-lit
      16,465  philosophy
      12,638  19th-century
       8,366  1001
       8,099  novella
       6,141  school
       4,984  classic-literature
       4,806  novellas
       4,450  1001-books-to-read-before-you-die
       4,005  short-story
       4,005  literary-fiction
       3,827  tolstoy
       3,706  classics
       3,560  read-for-school
       3,471  russians
       3,026  short
       3,026  historical-fiction
       2,759  read-in-2016
       2,759  leo-tolstoy
       2,670  for-school
       2,670  existentialism
       2,670  college
       2,639  fiction
       2,492  1800s
       2,403  translated
       2,403  my-library
       2,343  russian-classics
       2,314  drama
       2,225  classics-to-read
       2,225  translation
       2,136  1001-import
       2,047  read-in-2015
       1,958  to-read-classics
       1,958  audio
       1,871  high-school
       1,869  adult-fiction
       1,869  the-russians
       1,780  read-in-2017
       1,780  lit
       1,780  1001-books-to-read
       1,780  1001-books-you-must-read-before-you
       1,691  russian-authors
       1,691  read-in-2014
       1,691  literary
       1,691  school-books
       1,691  psychology
       1,691  general-fiction
       1,602  literature-russian
       1,602  death-and-dying
       1,602  1880s
       1,602  classic-lit
       1,513  literatura-russa
       1,513  short-fiction
       1,513  classic-fiction
       1,424  clásicos
       1,424  read-2016
       1,424  favorite-books
       1,424  favorite
       1,412  read-2017
       1,335  literatura
       1,335  favourite
       1,335  biblioteca
       1,335  europe
       1,335  religion
       1,335  in-translation
       1,246  literatura-rusa
       1,246  classici
       1,246  letteratura-russa
       1,246  school-reading
       1,246  to-reread
       1,246  world-literature
       1,246  1001-to-read
       1,157  to-re-read
       1,157  short-books
       1,157  favoritos
       1,157  history
       1,001  rússia
         156  adult

----------------------------------------------------------------------

=== The Hitchhiker's Guide to the Galaxy (Hitchhiker's Guide to the Galaxy, #1)
rating   4.20   ratings 1,023,775   reviews 20,974
genres   ['fantasy', 'fiction', 'paranormal', 'young-adult']

description:
Seconds before the Earth is demolished to make way for a galactic freeway, Arthur Dent is plucked off the planet by his friend Ford Prefect, a researcher for the revised edition of The Hitchhiker's Guide to the Galaxy who, for the last fifteen years, has been posing as an out-of-work actor.
Together this dynamic pair begin a journey through space aided by quotes from The Hitchhiker's Guide ("A towel is about the most massively useful thing an interstellar hitchhiker can have") and a galaxy-full of fellow travelers: Zaphod Beeblebrox--the two-headed, three-armed ex-hippie and totally out-to-lunch president of the galaxy; Trillian, Zaphod's girlfriend (formally Tricia McMillan), whom Arthur tried to pick up at a cocktail party once upon a time zone; Marvin, a paranoid, brilliant, and chronically depressed robot; Veet Voojagig, a former graduate student who is obsessed with the disappearance of all the ballpoint pens he bought over the years.

tags (72):
   1,466,882  science-fiction
   1,310,213  sci-fi
     945,085  fiction
     588,372  humor
     457,284  fantasy
     381,288  classics
     242,534  scifi
     192,173  humour
     191,835  comedy
     158,379  sci-fi-fantasy
     110,955  funny
      86,982  adventure
      83,762  sf
      79,779  classic
      69,168  fantasy-sci-fi
      61,439  adult
      59,212  scifi-fantasy
      49,518  1001-books
      45,588  british
      43,885  audio
      41,437  douglas-adams
      41,263  young-adult
      39,431  space
      39,191  english
      38,981  science-fiction-fantasy
      37,257  adult-fiction
      37,073  aliens
      32,224  satire
      30,785  1001
      30,261  literature
      30,261  novel
      29,344  science
      28,034  fun
      27,510  speculative-fiction
      26,855  sci-fi-and-fantasy
      25,807  20th-century
      25,700  audio-books
      24,890  fantasy-scifi
      24,550  my-library
      24,550  humorous
      24,235  favorite
      22,270  read-in-2014
      22,139  1001-books-to-read-before-you-die
      20,436  favorite-books
      20,043  read-in-2015
      20,043  to-re-read
      18,078  5-stars
      17,685  fantascienza
      17,423  read-in-2013
      17,030  audio-book
      16,899  ya
      16,897  contemporary
      16,244  read-in-english
      16,244  sf-fantasy
      16,115  own-it
      15,849  read-in-2016
      15,458  british-literature
      15,327  modern-classics
      15,196  to-reread
      15,130  séries
      15,087  read-in-2017
      15,065  must-read
      14,934  faves
      14,594  recommended
      14,148  read-more-than-once
      13,886  did-not-finish
      13,755  borrowed
      13,440  science-fiction-and-fantasy
      13,362  to-read-fiction
      12,969  hilarious
      12,838  1970s
      12,707  sff

----------------------------------------------------------------------

## Testing signal from description

tags might give some value, but they are too much to clean. if description can extract similar tags, they would not be needed.

In [17]:
from transformers import pipeline

clf = pipeline("text-classification",
               model="j-hartmann/emotion-english-distilroberta-base",
               top_k=None, truncation=True)

for q in ["Little Prince", "Ivan Ily", "Hitchhiker", "Dorian Gray"]:
    r = books[books.title.str.contains(q, case=False, na=False, regex=False)] \
            .nlargest(1, "ratings_total").iloc[0]
    scores = {d["label"]: round(d["score"], 3) for d in clf(r.description)[0]}
    print(f"{q:<16} {scores}")

/Users/navyajain/Downloads/projects/book-recommendation-engine/.venv/lib/python3.13/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm
Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
Loading weights: 100%|██████████| 105/105 [00:00<00:00, 18799.71it/s]

Little Prince    {'joy': 0.682, 'neutral': 0.262, 'fear': 0.014, 'surprise': 0.014, 'sadness': 0.013, 'disgust': 0.011, 'anger': 0.003}
Ivan Ily         {'surprise': 0.765, 'fear': 0.196, 'neutral': 0.018, 'sadness': 0.007, 'disgust': 0.005, 'anger': 0.005, 'joy': 0.003}
Hitchhiker       {'neutral': 0.869, 'surprise': 0.031, 'disgust': 0.03, 'anger': 0.024, 'joy': 0.023, 'fear': 0.016, 'sadness': 0.007}
Dorian Gray      {'disgust': 0.625, 'fear': 0.329, 'anger': 0.016, 'neutral': 0.013, 'sadness': 0.009, 'surprise': 0.006, 'joy': 0.003}

In [19]:
import requests

BASE = "https://mcauleylab.ucsd.edu/public_datasets/gdrive/goodreads"

r = requests.head(f"{BASE}/goodreads_interactions.csv", allow_redirects=True)
print(f"{int(r.headers['Content-Length']) / 1e9:.1f} GB")

4.3 GB

In [ ]:
books[["work_id", "book_id_all"]].to_parquet("../data/interim/catalog_ids.parquet", index=False)